version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

commands:
  install:
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "package.json" }}
          - dependency-cache-
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

jobs:
  retweet:
    <<: *defaults
    steps:
      - install
      - run: node index.js
      
parameters:
  run-schedule:
    type: boolean
    default: false

workflows:
  version: 2

  test:
    jobs:
     when:
      not: << pipeline.parameters.run-schedule >>
      - retweet

  poll:
    when: << pipeline.parameters.run-schedule >>
    jobs:
      - retweet
      
